### ISSUE TITLE
rbin: biased correlation parameter estimate using GEE

### ISSUE THREAD

**Issue by ayamitani** [AnestisTouloumis/SimCorMultRes#1]
I've noticed that the correlation estimate from fitting a GEE model (package gee) is consistently smaller than the true correlation parameter I enter in the rbin statement. In the example below, my true rho =  0.5 (exchangeable correlation structure) but the estimated rho in GEE is 0.2999. I've conducted a small simulation (n = 1000) and the estimated rho is consistently smaller. Fixed effects seem asymptotically unbiased. I would like to obtain unbiased correlation estimates as well as unbiased fixed effects. Please advise.

library(SimCorMultRes)
library(gee)

N <- 100
x <- rbinom(N, 1, prob = 0.5)
xvec <- rep(x, each = 3)

intercepts <- -1
betas <- 0.5

clsize <- 3
rho <- 0.5

cor.matrix <- matrix(ncol = 3, nrow = 3,
                     c(1, rho, rho,
                       rho, 1, rho,
                       rho, rho, 1))

CorBinRes <- rbin(clsize = clsize, intercepts = intercepts, betas = betas,
                  xformula = ~xvec, cor.matrix = cor.matrix, link = "logit")

binGEEmod <- gee(y ~ xvec, family = binomial("logit"), id = id, 
                 corstr = "exchangeable",
                 data = CorBinRes$simdata)
summary(binGEEmod)

> summary(binGEEmod)

 GEE:  GENERALIZED LINEAR MODELS FOR DEPENDENT DATA
 gee S-function, version 4.13 modified 98/01/27 (1998) 

Model:
 Link:                      Logit 
 Variance to Mean Relation: Binomial 
 Correlation Structure:     Exchangeable 

Call:
gee(formula = y ~ xvec, id = id, data = CorBinRes$simdata, family = binomial("logit"), 
    corstr = "exchangeable")

Summary of Residuals:
       Min         1Q     Median         3Q        Max 
-0.4184397 -0.4184397 -0.3270440  0.5815603  0.6729560 

Coefficients:
              Estimate Naive S.E.   Naive z Robust S.E.  Robust z
(Intercept) -0.7215851  0.2145247 -3.363646   0.2303582 -3.132448
xvec         0.3924033  0.3048868  1.287046   0.3020483  1.299141

Estimated Scale Parameter:  1.006711
Number of Iterations:  1

Working Correlation
         [,1]     [,2]     [,3]
[1,] 1.000000 0.299852 0.299852
[2,] 0.299852 1.000000 0.299852
[3,] 0.299852 0.299852 1.000000
>

**Comment by AnestisTouloumis** [comment]
This is because the two correlation parameters measure different association. The estimate of the correlation parameter from the GEE model corresponds to the estimated correlation coefficient between any two binary responses within a cluster. The value that you enter in SimCorMultRes corresponds to the true correlation coefficient between the latent continuous random variables, which are then discretized to produce the desired clustered binary responses utilizing the threshold approach described in [Touloumis (2016)](https://CRAN.R-project.org/package=SimCorMultRes).  In other words, this is not a bug of either SimCorMultRes or gee packages since you are comparing two different parameters.
